version: "3"

services:
  # Postgres
  postgres:
    image: "postgres:latest"
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      TZ: Europe/Paris
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Map port 6379 on the host to port 6379 in the container
    volumes:
      - redis-data:/var/lib/redis/data

# Persistent Data Volumes
volumes:
  postgres_data:
  redis-data:
