version: "1"

services:
  # PostgreSQL
  postgres:
    image: "postgres:15"
    command: postgres -c 'max_connections=200' -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c pg_stat_statements.max=10000
    ports:
      - "5433:5432" # Map port 5433 on the host to port 5432 in the container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=Europe/Paris
    labels:
      NAME: "flux-pg"
    volumes:
      - postgresql-data:/var/lib/postgresql-15/data

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672" # Map port 5673 on the host to port 5672 in the container
      - "15673:15672" # Map port 15673 on the host to port 15672 in the container

# Persistent Data Volumes
volumes:
  postgresql-data:
