version: "3"

services:
  # PostgreSQL
  postgres:
    image: "postgres:15"
    command: postgres -c 'max_connections=200' -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c pg_stat_statements.max=10000
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=Europe/Paris
    labels:
      NAME: "flux-pg"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Map port 6379 on the host to port 6379 in the container
    volumes:
      - redis-data:/data

# Persistent Data Volumes
volumes:
  postgresql-data:
  redis-data:
