version: '3'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: curlywire90
      POSTGRES_DB: sero_database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./packages/api
    env_file:
      - ./packages/api/config/.env
    ports:
      - "3336:3336"
    depends_on:
      - database

  bot:
    build:
      context: ./packages/bot
    env_file:
      - ./packages/bot/config/.env
    depends_on:
      - api

volumes:
  db_data:
