version: '3'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: curlywire90
      POSTGRES_DB: sero_database
      TZ: 'Europe/Paris'
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: ./packages/api
    environment:
      NODE_ENV: production
    env_file:
      - ./packages/api/config/.env
    restart: unless-stopped
    ports:
      - "3336:3336"
    depends_on:
      - database

  bot:
    build:
      context: ./packages/bot
    env_file:
      - ./packages/bot/config/.env
    environment:
      NODE_ENV: production
    restart: unless-stopped
    depends_on:
      - api

volumes:
  db_data:
