version: '3'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: curlywire90
      POSTGRES_DB: sero_database
      TZ: 'Europe/Paris'
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api:
    build:
      context: ./packages/api
    environment:
      NODE_ENV: production
    env_file:
      - ./packages/api/config/.env
    restart: unless-stopped
    ports:
      - "3336:3336"
    depends_on:
      - database
      - redis

  bot:
    build:
      context: ./packages/bot
    env_file:
      - ./packages/bot/config/.env
    environment:
      NODE_ENV: production
    restart: unless-stopped
    depends_on:
      - redis
      - api

volumes:
  db_data:
  redis-data:
