name: "CodeQL Code-check"

on:
  push:
    branches: [ main ] # Temp disabled by only checking main branch

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - run: npm ci
    - run: npm run build
    - run: rm -rf dist

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
