name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Hub credentials
        run: echo "${{ secrets.DOCKER_USERNAME }}\n${{ secrets.DOCKER_SECRET }}" > ~/.docker/config.json

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_SECRET }}

      - name: Build and push API Docker image
        run: |
          cd ./packages/api
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flux-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/flux-api:latest

      - name: Deploy API to Debian server
        run: |
          ssh flux@${{ secrets.SERVER_HOST }} "docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_SECRET }}"
          ssh flux@${{ secrets.SERVER_HOST }} "docker pull ${{ secrets.DOCKER_USERNAME }}/flux-api:latest"
          ssh flux@${{ secrets.SERVER_HOST }} "docker run -d -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/flux-api:latest"

  build-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Hub credentials
        run: echo "${{ secrets.DOCKER_USERNAME }}\n${{ secrets.DOCKER_SECRET }}" > ~/.docker/config.json

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_SECRET }}

      - name: Build and push Bot Docker image
        run: |
          cd ./packages/bot
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flux-bot:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/flux-bot:latest

      - name: Deploy Bot to Debian server
        run: |
          ssh flux@${{ secrets.SERVER_HOST }} "docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_SECRET }}"
          ssh flux@${{ secrets.SERVER_HOST }} "docker pull ${{ secrets.DOCKER_USERNAME }}/flux-bot:latest"
          ssh flux@${{ secrets.SERVER_HOST }} "docker run -d -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/flux-bot:latest"

