name: Build Docker Image and Execute Another Job

on:
  push:
    branches: [development, test-deploy]
  pull_request:
    types: [closed]

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.check-success.outputs.success }}
    steps:
      - name: Check if push or pull request was successful
        id: check-success
        run: echo "::set-output name=success::$(test ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) }})"
        
  build-bot:
    runs-on: ubuntu-latest
    needs: check-commit
    if: ${{ needs.check-success.outputs.success == 'true' }}

    steps:
      - uses: actions/checkout@v3
      - name: Test build Docker image
        run: docker build ./packages/bot --file ./packages/bot/Dockerfile --tag flux-bot:$(date +%s)