name: Test build API & Bot

on:
  push:
    branches: [development, test-deploy]
  pull_request:
    types: [closed]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test build Docker image API
        run: docker build ./packages/api --file ./packages/api/Dockerfile --tag flux-api:$(date +%s)

      - name: Success Message API
        run: echo "API Build successful!"

  build-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test build Docker image API
        run: docker build ./packages/bot --file ./packages/bot/Dockerfile --tag flux-bot:$(date +%s)

      - name: Success Message Bot
        run: echo "Bot Build successful!"
