name: Update Version

on:
  push:
    paths:
      - 'packages/**'
  pull_request:
    paths:
      - 'packages/**'

jobs:
  update_version:
    name: Update Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git configuration
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get changed files
        id: changed_files
        run: echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

      - name: Update version
        run: |
          files="${{ steps.changed_files.outputs.files }}"
          if echo "$files" | grep -qE 'packages/api/'; then
            npm version patch --prefix packages/api
          fi
          if echo "$files" | grep -qE 'packages/bot/'; then
            npm version patch --prefix packages/bot
          fi
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            npm version minor --prefix packages/api
            npm version minor --prefix packages/bot
          fi

      - name: Commit and push changes
        run: |
          git add -A
          git commit -m "Update version"
          git push
